#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XRelativeLayout.Resource", IsApplication=true)]

namespace XRelativeLayout
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Colombia = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int dolar = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int euro = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Fondo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int venezuela = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050009
			public const int btnSalir = 2131034121;
			
			// aapt resource value: 0x7f050004
			public const int btnconvertir = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int imageCol = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int imageVen = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int txtcapitalC = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int txtcapitalV = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int txtegresoV = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int txtegresosC = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int txtingresoV = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int txtingresosC = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int VistaCapital = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
